### PR TITLE
Compute sentence prob

### PR DESCRIPTION
**Pull request by DongjiGao**
Add get_sentence_prob.py that can compute sentence probability from input text file given language model in arpa form. The result would be written to an output file.

### CODE REVIEW

**Comment by danpovey** [comment]
I'm wondering whether it might make more sense to add this in Kaldi instead?
It seems to me that it's independent of where the LM comes from.
Remind me why we needed this.
Also, please use SRILM to verify that it's correct.  SRILM has an option to
compute the probs per word.

**Comment by DongjiGao** [comment]
Xiaohui needs a script to compute sentence probability like get_data_probs.py in pocolm.
https://github.com/danpovey/pocolm/issues/92
I have checked several sentences by hand and they seem correct. I will check with SRILM.

**Comment by danpovey** [comment]
OK, thanks.  When you've checked it, though, please show it to Xiaohui and
he can incorporate it into what he's doing directly, as a script that's in
Kaldi.  I think this may make more sense.

**Comment by DongjiGao** [comment]
Will do. It might take me some time since I have not used SRILM before.

**Pull request closed without merging**
