### PR TITLE
optimized the formula of computing the inverse Hessian in BFGS

### PR DESCRIPTION
**Pull request by keli78**

### CODE REVIEW

**Comment by danpovey** [comment]
Did you test that it still works with this change?

**Comment by danpovey** [comment]
it's OK, I'll  test myself.

**Comment by keli78** [comment]
Considering my modification is quite simple, I have thought it should be
fine. I tried to run the test code (egs/sefl_test/run.sh) while got an
error here:

wordlist_to_vocab.py: error: unrecognized arguments: --num-words=500
--weights=data/weights

I'll fix it soon and test it before I create a new pull request.

Ke

On Tue, May 17, 2016 at 1:05 AM, Daniel Povey notifications@github.com
wrote:

> Did you test that it still works with this change?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/danpovey/pocolm/pull/4#issuecomment-219620272

## 

Ke Li
Dept. of Electrical and Computer Engineering
Johns Hopkins University
Email: kli26@jhu.edu

**Comment by danpovey** [comment]
It's OK, I'm testing it and it seems to work.
That error is from a separate issue that I already fixed.

**Comment by keli78** [comment]
Ok, got it.
Ke

On Tue, May 17, 2016 at 1:26 AM, Daniel Povey notifications@github.com
wrote:

> It's OK, I'm testing it and it seems to work.
> That error is from a separate issue that I already fixed.
> 
> On Tue, May 17, 2016 at 1:22 AM, Ke Li notifications@github.com wrote:
> 
> > Considering my modification is quite simple, I have thought it should be
> > fine. I tried to run the test code (egs/sefl_test/run.sh) while got an
> > error here:
> > 
> > wordlist_to_vocab.py: error: unrecognized arguments: --num-words=500
> > --weights=data/weights
> > 
> > I'll fix it soon and test it before I create a new pull request.
> > 
> > Ke
> > 
> > On Tue, May 17, 2016 at 1:05 AM, Daniel Povey notifications@github.com
> > wrote:
> > 
> > > Did you test that it still works with this change?
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/danpovey/pocolm/pull/4#issuecomment-219620272
> > 
> > ## 
> > 
> > Ke Li
> > Dept. of Electrical and Computer Engineering
> > Johns Hopkins University
> > Email: kli26@jhu.edu
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > https://github.com/danpovey/pocolm/pull/4#issuecomment-219622111
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/danpovey/pocolm/pull/4#issuecomment-219622514

## 

Ke Li
Dept. of Electrical and Computer Engineering
Johns Hopkins University
Email: kli26@jhu.edu

**Pull request merged**
