### PR TITLE
Modify optimize_metaparameters.py to ensure at least a finite distanc…

### PR DESCRIPTION
**Pull request by danpovey**
…e between discounting values (prevents certain errors later on)

### CODE REVIEW

**Comment by vince62s** [comment]
Dan, 
Just for my full understanding.
in your above fix, you write the parameters with more decimals when very close to the limit.
However when you read the parameter and convert string to float don't you think we will lose
this precision ?

**Comment by danpovey** [comment]
I think there should be no loss of precision in reading-- AFAIK python uses
doubles throughout and there would be no reason to truncate.

**Comment by vince62s** [comment]
I reran, works fine, you can merge.

**Comment by danpovey** [comment]
Thanks!

**Pull request merged**
